/**
 * One-time data preparation script.
 * Generates static JSON files for country codes, language data, and language families.
 *
 * Run: npx tsx scripts/prepare-language-data.ts
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const DATA_DIR = join(__dirname, '..', 'src', 'data');
mkdirSync(DATA_DIR, { recursive: true });

// ISO 3166-1 numeric → alpha-2 mapping
// Source: https://en.wikipedia.org/wiki/ISO_3166-1
const countryCodeMap: Record<string, string> = {
  '004': 'AF', '008': 'AL', '010': 'AQ', '012': 'DZ', '016': 'AS',
  '020': 'AD', '024': 'AO', '028': 'AG', '031': 'AZ', '032': 'AR',
  '036': 'AU', '040': 'AT', '044': 'BS', '048': 'BH', '050': 'BD',
  '051': 'AM', '052': 'BB', '056': 'BE', '060': 'BM', '064': 'BT',
  '068': 'BO', '070': 'BA', '072': 'BW', '074': 'BV', '076': 'BR',
  '084': 'BZ', '086': 'IO', '090': 'SB', '092': 'VG', '096': 'BN',
  '100': 'BG', '104': 'MM', '108': 'BI', '112': 'BY', '116': 'KH',
  '120': 'CM', '124': 'CA', '132': 'CV', '136': 'KY', '140': 'CF',
  '144': 'LK', '148': 'TD', '152': 'CL', '156': 'CN', '158': 'TW',
  '162': 'CX', '166': 'CC', '170': 'CO', '174': 'KM', '175': 'YT',
  '178': 'CG', '180': 'CD', '184': 'CK', '188': 'CR', '191': 'HR',
  '192': 'CU', '196': 'CY', '203': 'CZ', '204': 'BJ', '208': 'DK',
  '212': 'DM', '214': 'DO', '218': 'EC', '222': 'SV', '226': 'GQ',
  '231': 'ET', '232': 'ER', '233': 'EE', '234': 'FO', '238': 'FK',
  '239': 'GS', '242': 'FJ', '246': 'FI', '248': 'AX', '250': 'FR',
  '254': 'GF', '258': 'PF', '260': 'TF', '262': 'DJ', '266': 'GA',
  '268': 'GE', '270': 'GM', '275': 'PS', '276': 'DE', '288': 'GH',
  '292': 'GI', '296': 'KI', '300': 'GR', '304': 'GL', '308': 'GD',
  '312': 'GP', '316': 'GU', '320': 'GT', '324': 'GN', '328': 'GY',
  '332': 'HT', '334': 'HM', '336': 'VA', '340': 'HN', '344': 'HK',
  '348': 'HU', '352': 'IS', '356': 'IN', '360': 'ID', '364': 'IR',
  '368': 'IQ', '372': 'IE', '376': 'IL', '380': 'IT', '384': 'CI',
  '388': 'JM', '392': 'JP', '398': 'KZ', '400': 'JO', '404': 'KE',
  '408': 'KP', '410': 'KR', '414': 'KW', '417': 'KG', '418': 'LA',
  '422': 'LB', '426': 'LS', '428': 'LV', '430': 'LR', '434': 'LY',
  '438': 'LI', '440': 'LT', '442': 'LU', '446': 'MO', '450': 'MG',
  '454': 'MW', '458': 'MY', '462': 'MV', '466': 'ML', '470': 'MT',
  '474': 'MQ', '478': 'MR', '480': 'MU', '484': 'MX', '492': 'MC',
  '496': 'MN', '498': 'MD', '499': 'ME', '500': 'MS', '504': 'MA',
  '508': 'MZ', '512': 'OM', '516': 'NA', '520': 'NR', '524': 'NP',
  '528': 'NL', '531': 'CW', '533': 'AW', '534': 'SX', '535': 'BQ',
  '540': 'NC', '548': 'VU', '554': 'NZ', '558': 'NI', '562': 'NE',
  '566': 'NG', '570': 'NU', '574': 'NF', '578': 'NO', '580': 'MP',
  '581': 'UM', '583': 'FM', '584': 'MH', '585': 'PW', '586': 'PK',
  '591': 'PA', '598': 'PG', '600': 'PY', '604': 'PE', '608': 'PH',
  '612': 'PN', '616': 'PL', '620': 'PT', '624': 'GW', '626': 'TL',
  '630': 'PR', '634': 'QA', '638': 'RE', '642': 'RO', '643': 'RU',
  '646': 'RW', '652': 'BL', '654': 'SH', '659': 'KN', '660': 'AI',
  '662': 'LC', '663': 'MF', '666': 'PM', '670': 'VC', '674': 'SM',
  '678': 'ST', '682': 'SA', '686': 'SN', '688': 'RS', '690': 'SC',
  '694': 'SL', '702': 'SG', '703': 'SK', '704': 'VN', '705': 'SI',
  '706': 'SO', '710': 'ZA', '716': 'ZW', '724': 'ES', '728': 'SS',
  '729': 'SD', '732': 'EH', '740': 'SR', '744': 'SJ', '748': 'SZ',
  '752': 'SE', '756': 'CH', '760': 'SY', '762': 'TJ', '764': 'TH',
  '768': 'TG', '772': 'TK', '776': 'TO', '780': 'TT', '784': 'AE',
  '788': 'TN', '792': 'TR', '795': 'TM', '796': 'TC', '798': 'TV',
  '800': 'UG', '804': 'UA', '807': 'MK', '818': 'EG', '826': 'GB',
  '831': 'GG', '832': 'JE', '833': 'IM', '834': 'TZ', '840': 'US',
  '850': 'VI', '854': 'BF', '858': 'UY', '860': 'UZ', '862': 'VE',
  '876': 'WF', '882': 'WS', '887': 'YE', '894': 'ZM',
  // Kosovo (not in ISO 3166-1 but in world-atlas as -99)
  '-99': 'XK',
};

// Per-country language data
// languages: ISO 639 variant codes of official/major languages
// (mostly ISO 639-1, with specific macrolanguage splits like arb/cmn)
// primaryFamily: the language family of the primary official language
const languageData: Record<string, { name: string; languages: string[]; primaryFamily: string }> = {
  AF: { name: 'Afghanistan', languages: ['ps', 'fa'], primaryFamily: 'Indo-European' },
  AL: { name: 'Albania', languages: ['sq'], primaryFamily: 'Indo-European' },
  DZ: { name: 'Algeria', languages: ['arb', 'fr'], primaryFamily: 'Afro-Asiatic' },
  AD: { name: 'Andorra', languages: ['ca'], primaryFamily: 'Indo-European' },
  AO: { name: 'Angola', languages: ['pt'], primaryFamily: 'Indo-European' },
  AG: { name: 'Antigua and Barbuda', languages: ['en'], primaryFamily: 'Indo-European' },
  AR: { name: 'Argentina', languages: ['es'], primaryFamily: 'Indo-European' },
  AM: { name: 'Armenia', languages: ['hy'], primaryFamily: 'Indo-European' },
  AU: { name: 'Australia', languages: ['en'], primaryFamily: 'Indo-European' },
  AT: { name: 'Austria', languages: ['de'], primaryFamily: 'Indo-European' },
  AZ: { name: 'Azerbaijan', languages: ['az'], primaryFamily: 'Turkic' },
  BS: { name: 'Bahamas', languages: ['en'], primaryFamily: 'Indo-European' },
  BH: { name: 'Bahrain', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  BD: { name: 'Bangladesh', languages: ['bn'], primaryFamily: 'Indo-European' },
  BB: { name: 'Barbados', languages: ['en'], primaryFamily: 'Indo-European' },
  BY: { name: 'Belarus', languages: ['be', 'ru'], primaryFamily: 'Indo-European' },
  BE: { name: 'Belgium', languages: ['nl', 'fr', 'de'], primaryFamily: 'Indo-European' },
  BZ: { name: 'Belize', languages: ['en', 'es'], primaryFamily: 'Indo-European' },
  BJ: { name: 'Benin', languages: ['fr'], primaryFamily: 'Indo-European' },
  BT: { name: 'Bhutan', languages: ['dz'], primaryFamily: 'Sino-Tibetan' },
  BO: { name: 'Bolivia', languages: ['es', 'qu', 'ay'], primaryFamily: 'Indo-European' },
  BA: { name: 'Bosnia and Herzegovina', languages: ['bs', 'hr', 'sr'], primaryFamily: 'Indo-European' },
  BW: { name: 'Botswana', languages: ['en', 'tn'], primaryFamily: 'Indo-European' },
  BR: { name: 'Brazil', languages: ['pt'], primaryFamily: 'Indo-European' },
  BN: { name: 'Brunei', languages: ['ms'], primaryFamily: 'Austronesian' },
  BG: { name: 'Bulgaria', languages: ['bg'], primaryFamily: 'Indo-European' },
  BF: { name: 'Burkina Faso', languages: ['fr'], primaryFamily: 'Indo-European' },
  BI: { name: 'Burundi', languages: ['rn', 'fr'], primaryFamily: 'Niger-Congo' },
  KH: { name: 'Cambodia', languages: ['km'], primaryFamily: 'Austroasiatic' },
  CM: { name: 'Cameroon', languages: ['fr', 'en'], primaryFamily: 'Indo-European' },
  CA: { name: 'Canada', languages: ['en', 'fr'], primaryFamily: 'Indo-European' },
  CV: { name: 'Cape Verde', languages: ['pt'], primaryFamily: 'Indo-European' },
  CF: { name: 'Central African Republic', languages: ['fr', 'sg'], primaryFamily: 'Indo-European' },
  TD: { name: 'Chad', languages: ['fr', 'arb'], primaryFamily: 'Indo-European' },
  CL: { name: 'Chile', languages: ['es'], primaryFamily: 'Indo-European' },
  CN: { name: 'China', languages: ['cmn'], primaryFamily: 'Sino-Tibetan' },
  CO: { name: 'Colombia', languages: ['es'], primaryFamily: 'Indo-European' },
  KM: { name: 'Comoros', languages: ['arb', 'fr'], primaryFamily: 'Afro-Asiatic' },
  CG: { name: 'Republic of the Congo', languages: ['fr'], primaryFamily: 'Indo-European' },
  CD: { name: 'Democratic Republic of the Congo', languages: ['fr'], primaryFamily: 'Indo-European' },
  CR: { name: 'Costa Rica', languages: ['es'], primaryFamily: 'Indo-European' },
  CI: { name: "Côte d'Ivoire", languages: ['fr'], primaryFamily: 'Indo-European' },
  HR: { name: 'Croatia', languages: ['hr'], primaryFamily: 'Indo-European' },
  CU: { name: 'Cuba', languages: ['es'], primaryFamily: 'Indo-European' },
  CY: { name: 'Cyprus', languages: ['el', 'tr'], primaryFamily: 'Indo-European' },
  CZ: { name: 'Czechia', languages: ['cs'], primaryFamily: 'Indo-European' },
  DK: { name: 'Denmark', languages: ['da'], primaryFamily: 'Indo-European' },
  DJ: { name: 'Djibouti', languages: ['fr', 'arb'], primaryFamily: 'Indo-European' },
  DM: { name: 'Dominica', languages: ['en'], primaryFamily: 'Indo-European' },
  DO: { name: 'Dominican Republic', languages: ['es'], primaryFamily: 'Indo-European' },
  EC: { name: 'Ecuador', languages: ['es'], primaryFamily: 'Indo-European' },
  EG: { name: 'Egypt', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  SV: { name: 'El Salvador', languages: ['es'], primaryFamily: 'Indo-European' },
  GQ: { name: 'Equatorial Guinea', languages: ['es', 'fr', 'pt'], primaryFamily: 'Indo-European' },
  ER: { name: 'Eritrea', languages: ['ti', 'arb', 'en'], primaryFamily: 'Afro-Asiatic' },
  EE: { name: 'Estonia', languages: ['et'], primaryFamily: 'Uralic' },
  SZ: { name: 'Eswatini', languages: ['en', 'ss'], primaryFamily: 'Indo-European' },
  ET: { name: 'Ethiopia', languages: ['am'], primaryFamily: 'Afro-Asiatic' },
  FJ: { name: 'Fiji', languages: ['en', 'fj', 'hi'], primaryFamily: 'Indo-European' },
  FI: { name: 'Finland', languages: ['fi', 'sv'], primaryFamily: 'Uralic' },
  FR: { name: 'France', languages: ['fr'], primaryFamily: 'Indo-European' },
  GA: { name: 'Gabon', languages: ['fr'], primaryFamily: 'Indo-European' },
  GM: { name: 'Gambia', languages: ['en'], primaryFamily: 'Indo-European' },
  GE: { name: 'Georgia', languages: ['ka'], primaryFamily: 'Kartvelian' },
  DE: { name: 'Germany', languages: ['de'], primaryFamily: 'Indo-European' },
  GH: { name: 'Ghana', languages: ['en'], primaryFamily: 'Indo-European' },
  GR: { name: 'Greece', languages: ['el'], primaryFamily: 'Indo-European' },
  GD: { name: 'Grenada', languages: ['en'], primaryFamily: 'Indo-European' },
  GT: { name: 'Guatemala', languages: ['es'], primaryFamily: 'Indo-European' },
  GN: { name: 'Guinea', languages: ['fr'], primaryFamily: 'Indo-European' },
  GW: { name: 'Guinea-Bissau', languages: ['pt'], primaryFamily: 'Indo-European' },
  GY: { name: 'Guyana', languages: ['en'], primaryFamily: 'Indo-European' },
  HT: { name: 'Haiti', languages: ['fr', 'ht'], primaryFamily: 'Indo-European' },
  HN: { name: 'Honduras', languages: ['es'], primaryFamily: 'Indo-European' },
  HU: { name: 'Hungary', languages: ['hu'], primaryFamily: 'Uralic' },
  IS: { name: 'Iceland', languages: ['is'], primaryFamily: 'Indo-European' },
  IN: { name: 'India', languages: ['hi', 'en'], primaryFamily: 'Indo-European' },
  ID: { name: 'Indonesia', languages: ['id'], primaryFamily: 'Austronesian' },
  IR: { name: 'Iran', languages: ['fa'], primaryFamily: 'Indo-European' },
  IQ: { name: 'Iraq', languages: ['arb', 'ku'], primaryFamily: 'Afro-Asiatic' },
  IE: { name: 'Ireland', languages: ['en', 'ga'], primaryFamily: 'Indo-European' },
  IL: { name: 'Israel', languages: ['he', 'arb'], primaryFamily: 'Afro-Asiatic' },
  IT: { name: 'Italy', languages: ['it'], primaryFamily: 'Indo-European' },
  JM: { name: 'Jamaica', languages: ['en'], primaryFamily: 'Indo-European' },
  JP: { name: 'Japan', languages: ['ja'], primaryFamily: 'Japonic' },
  JO: { name: 'Jordan', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  KZ: { name: 'Kazakhstan', languages: ['kk', 'ru'], primaryFamily: 'Turkic' },
  KE: { name: 'Kenya', languages: ['en', 'sw'], primaryFamily: 'Indo-European' },
  KI: { name: 'Kiribati', languages: ['en'], primaryFamily: 'Indo-European' },
  KP: { name: 'North Korea', languages: ['ko'], primaryFamily: 'Koreanic' },
  KR: { name: 'South Korea', languages: ['ko'], primaryFamily: 'Koreanic' },
  KW: { name: 'Kuwait', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  KG: { name: 'Kyrgyzstan', languages: ['ky', 'ru'], primaryFamily: 'Turkic' },
  LA: { name: 'Laos', languages: ['lo'], primaryFamily: 'Kra-Dai' },
  LV: { name: 'Latvia', languages: ['lv'], primaryFamily: 'Indo-European' },
  LB: { name: 'Lebanon', languages: ['arb', 'fr'], primaryFamily: 'Afro-Asiatic' },
  LS: { name: 'Lesotho', languages: ['en', 'st'], primaryFamily: 'Indo-European' },
  LR: { name: 'Liberia', languages: ['en'], primaryFamily: 'Indo-European' },
  LY: { name: 'Libya', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  LI: { name: 'Liechtenstein', languages: ['de'], primaryFamily: 'Indo-European' },
  LT: { name: 'Lithuania', languages: ['lt'], primaryFamily: 'Indo-European' },
  LU: { name: 'Luxembourg', languages: ['lb', 'fr', 'de'], primaryFamily: 'Indo-European' },
  MG: { name: 'Madagascar', languages: ['mg', 'fr'], primaryFamily: 'Austronesian' },
  MW: { name: 'Malawi', languages: ['en', 'ny'], primaryFamily: 'Indo-European' },
  MY: { name: 'Malaysia', languages: ['ms'], primaryFamily: 'Austronesian' },
  MV: { name: 'Maldives', languages: ['dv'], primaryFamily: 'Indo-European' },
  ML: { name: 'Mali', languages: ['fr'], primaryFamily: 'Indo-European' },
  MT: { name: 'Malta', languages: ['mt', 'en'], primaryFamily: 'Afro-Asiatic' },
  MR: { name: 'Mauritania', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  MU: { name: 'Mauritius', languages: ['en', 'fr'], primaryFamily: 'Indo-European' },
  MX: { name: 'Mexico', languages: ['es'], primaryFamily: 'Indo-European' },
  MD: { name: 'Moldova', languages: ['ro'], primaryFamily: 'Indo-European' },
  MC: { name: 'Monaco', languages: ['fr'], primaryFamily: 'Indo-European' },
  MN: { name: 'Mongolia', languages: ['mn'], primaryFamily: 'Mongolic' },
  ME: { name: 'Montenegro', languages: ['sr'], primaryFamily: 'Indo-European' },
  MA: { name: 'Morocco', languages: ['arb', 'fr'], primaryFamily: 'Afro-Asiatic' },
  MZ: { name: 'Mozambique', languages: ['pt'], primaryFamily: 'Indo-European' },
  MM: { name: 'Myanmar', languages: ['my'], primaryFamily: 'Sino-Tibetan' },
  NA: { name: 'Namibia', languages: ['en'], primaryFamily: 'Indo-European' },
  NR: { name: 'Nauru', languages: ['na', 'en'], primaryFamily: 'Austronesian' },
  NP: { name: 'Nepal', languages: ['ne'], primaryFamily: 'Indo-European' },
  NL: { name: 'Netherlands', languages: ['nl'], primaryFamily: 'Indo-European' },
  NZ: { name: 'New Zealand', languages: ['en', 'mi'], primaryFamily: 'Indo-European' },
  NI: { name: 'Nicaragua', languages: ['es'], primaryFamily: 'Indo-European' },
  NE: { name: 'Niger', languages: ['fr'], primaryFamily: 'Indo-European' },
  NG: { name: 'Nigeria', languages: ['en'], primaryFamily: 'Indo-European' },
  MK: { name: 'North Macedonia', languages: ['mk'], primaryFamily: 'Indo-European' },
  NO: { name: 'Norway', languages: ['no', 'nb', 'nn'], primaryFamily: 'Indo-European' },
  OM: { name: 'Oman', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  PK: { name: 'Pakistan', languages: ['ur', 'en'], primaryFamily: 'Indo-European' },
  PW: { name: 'Palau', languages: ['en'], primaryFamily: 'Indo-European' },
  PS: { name: 'Palestine', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  PA: { name: 'Panama', languages: ['es'], primaryFamily: 'Indo-European' },
  PG: { name: 'Papua New Guinea', languages: ['en', 'tpi'], primaryFamily: 'Indo-European' },
  PY: { name: 'Paraguay', languages: ['es', 'gn'], primaryFamily: 'Indo-European' },
  PE: { name: 'Peru', languages: ['es', 'qu'], primaryFamily: 'Indo-European' },
  PH: { name: 'Philippines', languages: ['tl', 'en'], primaryFamily: 'Austronesian' },
  PL: { name: 'Poland', languages: ['pl'], primaryFamily: 'Indo-European' },
  PT: { name: 'Portugal', languages: ['pt'], primaryFamily: 'Indo-European' },
  QA: { name: 'Qatar', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  RO: { name: 'Romania', languages: ['ro'], primaryFamily: 'Indo-European' },
  RU: { name: 'Russia', languages: ['ru'], primaryFamily: 'Indo-European' },
  RW: { name: 'Rwanda', languages: ['rw', 'fr', 'en'], primaryFamily: 'Niger-Congo' },
  KN: { name: 'Saint Kitts and Nevis', languages: ['en'], primaryFamily: 'Indo-European' },
  LC: { name: 'Saint Lucia', languages: ['en'], primaryFamily: 'Indo-European' },
  VC: { name: 'Saint Vincent and the Grenadines', languages: ['en'], primaryFamily: 'Indo-European' },
  WS: { name: 'Samoa', languages: ['sm', 'en'], primaryFamily: 'Austronesian' },
  SM: { name: 'San Marino', languages: ['it'], primaryFamily: 'Indo-European' },
  ST: { name: 'São Tomé and Príncipe', languages: ['pt'], primaryFamily: 'Indo-European' },
  SA: { name: 'Saudi Arabia', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  SN: { name: 'Senegal', languages: ['fr'], primaryFamily: 'Indo-European' },
  RS: { name: 'Serbia', languages: ['sr'], primaryFamily: 'Indo-European' },
  SC: { name: 'Seychelles', languages: ['fr', 'en'], primaryFamily: 'Indo-European' },
  SL: { name: 'Sierra Leone', languages: ['en'], primaryFamily: 'Indo-European' },
  SG: { name: 'Singapore', languages: ['en', 'ms', 'cmn', 'ta'], primaryFamily: 'Indo-European' },
  SK: { name: 'Slovakia', languages: ['sk'], primaryFamily: 'Indo-European' },
  SI: { name: 'Slovenia', languages: ['sl'], primaryFamily: 'Indo-European' },
  SB: { name: 'Solomon Islands', languages: ['en'], primaryFamily: 'Indo-European' },
  SO: { name: 'Somalia', languages: ['so', 'arb'], primaryFamily: 'Afro-Asiatic' },
  ZA: { name: 'South Africa', languages: ['af', 'en', 'zu', 'xh'], primaryFamily: 'Indo-European' },
  SS: { name: 'South Sudan', languages: ['en'], primaryFamily: 'Indo-European' },
  ES: { name: 'Spain', languages: ['es'], primaryFamily: 'Indo-European' },
  LK: { name: 'Sri Lanka', languages: ['si', 'ta'], primaryFamily: 'Indo-European' },
  SD: { name: 'Sudan', languages: ['arb', 'en'], primaryFamily: 'Afro-Asiatic' },
  SR: { name: 'Suriname', languages: ['nl'], primaryFamily: 'Indo-European' },
  SE: { name: 'Sweden', languages: ['sv'], primaryFamily: 'Indo-European' },
  CH: { name: 'Switzerland', languages: ['de', 'fr', 'it', 'rm'], primaryFamily: 'Indo-European' },
  SY: { name: 'Syria', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  TW: { name: 'Taiwan', languages: ['cmn'], primaryFamily: 'Sino-Tibetan' },
  TJ: { name: 'Tajikistan', languages: ['tg'], primaryFamily: 'Indo-European' },
  TZ: { name: 'Tanzania', languages: ['sw', 'en'], primaryFamily: 'Niger-Congo' },
  TH: { name: 'Thailand', languages: ['th'], primaryFamily: 'Kra-Dai' },
  TL: { name: 'Timor-Leste', languages: ['pt', 'tet'], primaryFamily: 'Indo-European' },
  TG: { name: 'Togo', languages: ['fr'], primaryFamily: 'Indo-European' },
  TO: { name: 'Tonga', languages: ['to', 'en'], primaryFamily: 'Austronesian' },
  TT: { name: 'Trinidad and Tobago', languages: ['en'], primaryFamily: 'Indo-European' },
  TN: { name: 'Tunisia', languages: ['arb', 'fr'], primaryFamily: 'Afro-Asiatic' },
  TR: { name: 'Turkey', languages: ['tr'], primaryFamily: 'Turkic' },
  TM: { name: 'Turkmenistan', languages: ['tk'], primaryFamily: 'Turkic' },
  TV: { name: 'Tuvalu', languages: ['en'], primaryFamily: 'Indo-European' },
  UG: { name: 'Uganda', languages: ['en', 'sw'], primaryFamily: 'Indo-European' },
  UA: { name: 'Ukraine', languages: ['uk'], primaryFamily: 'Indo-European' },
  AE: { name: 'United Arab Emirates', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  GB: { name: 'United Kingdom', languages: ['en'], primaryFamily: 'Indo-European' },
  US: { name: 'United States', languages: ['en', 'es'], primaryFamily: 'Indo-European' },
  UY: { name: 'Uruguay', languages: ['es'], primaryFamily: 'Indo-European' },
  UZ: { name: 'Uzbekistan', languages: ['uz'], primaryFamily: 'Turkic' },
  VU: { name: 'Vanuatu', languages: ['en', 'fr', 'bi'], primaryFamily: 'Indo-European' },
  VE: { name: 'Venezuela', languages: ['es'], primaryFamily: 'Indo-European' },
  VN: { name: 'Vietnam', languages: ['vi'], primaryFamily: 'Austroasiatic' },
  YE: { name: 'Yemen', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  ZM: { name: 'Zambia', languages: ['en'], primaryFamily: 'Indo-European' },
  ZW: { name: 'Zimbabwe', languages: ['en', 'sn', 'nd'], primaryFamily: 'Indo-European' },
  XK: { name: 'Kosovo', languages: ['sq', 'sr'], primaryFamily: 'Indo-European' },
  NC: { name: 'New Caledonia', languages: ['fr'], primaryFamily: 'Indo-European' },
  EH: { name: 'Western Sahara', languages: ['arb'], primaryFamily: 'Afro-Asiatic' },
  FK: { name: 'Falkland Islands', languages: ['en'], primaryFamily: 'Indo-European' },
  GL: { name: 'Greenland', languages: ['kl', 'da'], primaryFamily: 'Eskimo-Aleut' },
  GF: { name: 'French Guiana', languages: ['fr'], primaryFamily: 'Indo-European' },
  PR: { name: 'Puerto Rico', languages: ['es', 'en'], primaryFamily: 'Indo-European' },
};

// Language families and per-language info
const languageFamilies: Record<string, { name: string; nativeName: string; family: string }> = {
  af: { name: 'Afrikaans', nativeName: 'Afrikaans', family: 'Indo-European' },
  am: { name: 'Amharic', nativeName: 'አማርኛ', family: 'Afro-Asiatic' },
  arb: { name: 'Modern Standard Arabic', nativeName: 'العربية الفصحى', family: 'Afro-Asiatic' },
  ay: { name: 'Aymara', nativeName: 'Aymar aru', family: 'Aymaran' },
  az: { name: 'Azerbaijani', nativeName: 'Azərbaycan dili', family: 'Turkic' },
  be: { name: 'Belarusian', nativeName: 'Беларуская', family: 'Indo-European' },
  bg: { name: 'Bulgarian', nativeName: 'Български', family: 'Indo-European' },
  bi: { name: 'Bislama', nativeName: 'Bislama', family: 'Creole' },
  bn: { name: 'Bengali', nativeName: 'বাংলা', family: 'Indo-European' },
  bs: { name: 'Bosnian', nativeName: 'Bosanski', family: 'Indo-European' },
  ca: { name: 'Catalan', nativeName: 'Català', family: 'Indo-European' },
  cs: { name: 'Czech', nativeName: 'Čeština', family: 'Indo-European' },
  da: { name: 'Danish', nativeName: 'Dansk', family: 'Indo-European' },
  de: { name: 'German', nativeName: 'Deutsch', family: 'Indo-European' },
  dv: { name: 'Dhivehi', nativeName: 'ދިވެހި', family: 'Indo-European' },
  dz: { name: 'Dzongkha', nativeName: 'རྫོང་ཁ', family: 'Sino-Tibetan' },
  el: { name: 'Greek', nativeName: 'Ελληνικά', family: 'Indo-European' },
  en: { name: 'English', nativeName: 'English', family: 'Indo-European' },
  es: { name: 'Spanish', nativeName: 'Español', family: 'Indo-European' },
  et: { name: 'Estonian', nativeName: 'Eesti', family: 'Uralic' },
  fa: { name: 'Persian', nativeName: 'فارسی', family: 'Indo-European' },
  fi: { name: 'Finnish', nativeName: 'Suomi', family: 'Uralic' },
  fj: { name: 'Fijian', nativeName: 'Vosa Vakaviti', family: 'Austronesian' },
  fr: { name: 'French', nativeName: 'Français', family: 'Indo-European' },
  ga: { name: 'Irish', nativeName: 'Gaeilge', family: 'Indo-European' },
  gn: { name: 'Guarani', nativeName: "Avañe'ẽ", family: 'Tupian' },
  he: { name: 'Hebrew', nativeName: 'עברית', family: 'Afro-Asiatic' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी', family: 'Indo-European' },
  hr: { name: 'Croatian', nativeName: 'Hrvatski', family: 'Indo-European' },
  ht: { name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen', family: 'Creole' },
  hu: { name: 'Hungarian', nativeName: 'Magyar', family: 'Uralic' },
  hy: { name: 'Armenian', nativeName: 'Հայերեն', family: 'Indo-European' },
  id: { name: 'Indonesian', nativeName: 'Bahasa Indonesia', family: 'Austronesian' },
  is: { name: 'Icelandic', nativeName: 'Íslenska', family: 'Indo-European' },
  it: { name: 'Italian', nativeName: 'Italiano', family: 'Indo-European' },
  ja: { name: 'Japanese', nativeName: '日本語', family: 'Japonic' },
  ka: { name: 'Georgian', nativeName: 'ქართული', family: 'Kartvelian' },
  kk: { name: 'Kazakh', nativeName: 'Қазақ тілі', family: 'Turkic' },
  kl: { name: 'Kalaallisut', nativeName: 'Kalaallisut', family: 'Eskimo-Aleut' },
  km: { name: 'Khmer', nativeName: 'ភាសាខ្មែរ', family: 'Austroasiatic' },
  ko: { name: 'Korean', nativeName: '한국어', family: 'Koreanic' },
  ku: { name: 'Kurdish', nativeName: 'Kurdî', family: 'Indo-European' },
  ky: { name: 'Kyrgyz', nativeName: 'Кыргызча', family: 'Turkic' },
  lb: { name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', family: 'Indo-European' },
  lo: { name: 'Lao', nativeName: 'ລາວ', family: 'Kra-Dai' },
  lt: { name: 'Lithuanian', nativeName: 'Lietuvių', family: 'Indo-European' },
  lv: { name: 'Latvian', nativeName: 'Latviešu', family: 'Indo-European' },
  mg: { name: 'Malagasy', nativeName: 'Malagasy', family: 'Austronesian' },
  mi: { name: 'Maori', nativeName: 'Te Reo Māori', family: 'Austronesian' },
  mk: { name: 'Macedonian', nativeName: 'Македонски', family: 'Indo-European' },
  mn: { name: 'Mongolian', nativeName: 'Монгол', family: 'Mongolic' },
  ms: { name: 'Malay', nativeName: 'Bahasa Melayu', family: 'Austronesian' },
  mt: { name: 'Maltese', nativeName: 'Malti', family: 'Afro-Asiatic' },
  my: { name: 'Burmese', nativeName: 'မြန်မာစာ', family: 'Sino-Tibetan' },
  na: { name: 'Nauruan', nativeName: 'Dorerin Naoero', family: 'Austronesian' },
  nb: { name: 'Norwegian Bokmål', nativeName: 'Norsk bokmål', family: 'Indo-European' },
  nd: { name: 'Northern Ndebele', nativeName: 'isiNdebele', family: 'Niger-Congo' },
  ne: { name: 'Nepali', nativeName: 'नेपाली', family: 'Indo-European' },
  nl: { name: 'Dutch', nativeName: 'Nederlands', family: 'Indo-European' },
  nn: { name: 'Norwegian Nynorsk', nativeName: 'Norsk nynorsk', family: 'Indo-European' },
  no: { name: 'Norwegian', nativeName: 'Norsk', family: 'Indo-European' },
  ny: { name: 'Chewa', nativeName: 'Chichewa', family: 'Niger-Congo' },
  pl: { name: 'Polish', nativeName: 'Polski', family: 'Indo-European' },
  ps: { name: 'Pashto', nativeName: 'پښتو', family: 'Indo-European' },
  pt: { name: 'Portuguese', nativeName: 'Português', family: 'Indo-European' },
  qu: { name: 'Quechua', nativeName: 'Runasimi', family: 'Quechuan' },
  rm: { name: 'Romansh', nativeName: 'Rumantsch', family: 'Indo-European' },
  rn: { name: 'Kirundi', nativeName: 'Ikirundi', family: 'Niger-Congo' },
  ro: { name: 'Romanian', nativeName: 'Română', family: 'Indo-European' },
  ru: { name: 'Russian', nativeName: 'Русский', family: 'Indo-European' },
  rw: { name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', family: 'Niger-Congo' },
  sg: { name: 'Sango', nativeName: 'Sängö', family: 'Creole' },
  si: { name: 'Sinhala', nativeName: 'සිංහල', family: 'Indo-European' },
  sk: { name: 'Slovak', nativeName: 'Slovenčina', family: 'Indo-European' },
  sl: { name: 'Slovenian', nativeName: 'Slovenščina', family: 'Indo-European' },
  sm: { name: 'Samoan', nativeName: 'Gagana Samoa', family: 'Austronesian' },
  sn: { name: 'Shona', nativeName: 'chiShona', family: 'Niger-Congo' },
  so: { name: 'Somali', nativeName: 'Soomaali', family: 'Afro-Asiatic' },
  sq: { name: 'Albanian', nativeName: 'Shqip', family: 'Indo-European' },
  sr: { name: 'Serbian', nativeName: 'Српски', family: 'Indo-European' },
  ss: { name: 'Swati', nativeName: 'SiSwati', family: 'Niger-Congo' },
  st: { name: 'Southern Sotho', nativeName: 'Sesotho', family: 'Niger-Congo' },
  sv: { name: 'Swedish', nativeName: 'Svenska', family: 'Indo-European' },
  sw: { name: 'Swahili', nativeName: 'Kiswahili', family: 'Niger-Congo' },
  ta: { name: 'Tamil', nativeName: 'தமிழ்', family: 'Dravidian' },
  tet: { name: 'Tetum', nativeName: 'Tetun', family: 'Austronesian' },
  tg: { name: 'Tajik', nativeName: 'Тоҷикӣ', family: 'Indo-European' },
  th: { name: 'Thai', nativeName: 'ไทย', family: 'Kra-Dai' },
  ti: { name: 'Tigrinya', nativeName: 'ትግርኛ', family: 'Afro-Asiatic' },
  tk: { name: 'Turkmen', nativeName: 'Türkmençe', family: 'Turkic' },
  tl: { name: 'Filipino', nativeName: 'Filipino', family: 'Austronesian' },
  tn: { name: 'Tswana', nativeName: 'Setswana', family: 'Niger-Congo' },
  to: { name: 'Tongan', nativeName: 'Lea Fakatonga', family: 'Austronesian' },
  tpi: { name: 'Tok Pisin', nativeName: 'Tok Pisin', family: 'Creole' },
  tr: { name: 'Turkish', nativeName: 'Türkçe', family: 'Turkic' },
  uk: { name: 'Ukrainian', nativeName: 'Українська', family: 'Indo-European' },
  ur: { name: 'Urdu', nativeName: 'اردو', family: 'Indo-European' },
  uz: { name: 'Uzbek', nativeName: "O'zbek", family: 'Turkic' },
  vi: { name: 'Vietnamese', nativeName: 'Tiếng Việt', family: 'Austroasiatic' },
  xh: { name: 'Xhosa', nativeName: 'isiXhosa', family: 'Niger-Congo' },
  cmn: { name: 'Mandarin Chinese', nativeName: '普通话', family: 'Sino-Tibetan' },
  zu: { name: 'Zulu', nativeName: 'isiZulu', family: 'Niger-Congo' },
};

// Write output files
writeFileSync(
  join(DATA_DIR, 'country-code-map.json'),
  JSON.stringify(countryCodeMap, null, 2)
);
console.log('✓ country-code-map.json');

writeFileSync(
  join(DATA_DIR, 'language-data.json'),
  JSON.stringify(languageData, null, 2)
);
console.log('✓ language-data.json');

writeFileSync(
  join(DATA_DIR, 'language-families.json'),
  JSON.stringify(languageFamilies, null, 2)
);
console.log('✓ language-families.json');

console.log(`\nGenerated 3 files in ${DATA_DIR}`);
console.log(`  Countries: ${Object.keys(countryCodeMap).length}`);
console.log(`  Language entries: ${Object.keys(languageData).length}`);
console.log(`  Languages: ${Object.keys(languageFamilies).length}`);
